[package]
name = "rust-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
[profile.dev]
panic = "abort"
debug-assertions = true # !
incremental = false
codegen-units = 1
opt-level = 'z' # !
debug = 2
overflow-checks = false
